name: on_green
on:
  workflow_call:
  workflow_run:
    workflows: [dep1, dep2]
    types: [completed]

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          console.info(context);
