name: dep2
on: push
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const sleep = new Promise((reject, resolve) => {
              setTimeout(() => resolve(), 5000);
            });
            const t = await sleep;
            console.log(context)